name: Deploy to ghcr.io

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: deploy-${{ github.ref }} # This ensures all runs for a branch are grouped
  cancel-in-progress: true # Cancels any in-progress runs for this group

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses: actions/checkout@v3  

      - name: Setup Docker BuildX 
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          # github.repository_owner and github.repository are hardcoded
          tags: ghcr.io/kth-cdate-courses/dd2482-executable-tutorial-trial-run:latest,ghcr.io/kth-cdate-courses/dd2482-executable-tutorial-trial-run:${{ github.sha }}
